import type { Product } from "@/lib/types";

export const CATEGORIES = [
  "Semua",
  "Roti Manis",
  "Roti Tawar",
  "Pastry",
  "Donat",
] as const;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "roti-kasur-manis",
    name: "Roti Kasur Manis",
    description:
      "Roti kasur lembut dengan taburan gula dan olesan mentega, dipanggang segar setiap pagi.",
    price: 15000,
    stock: 12,
    imageUrl: "/products/roti-kasur-manis.svg",
    category: "Roti Manis",
  },
  {
    id: "roti-coklat-keju",
    name: "Roti Coklat Keju",
    description: "Isian coklat lumer dan keju parut di atasnya, favorit anak-anak.",
    price: 12000,
    stock: 8,
    imageUrl: "/products/roti-coklat-keju.svg",
    category: "Roti Manis",
  },
  {
    id: "roti-tawar-gandum",
    name: "Roti Tawar Gandum",
    description: "Roti tawar sehat berbahan gandum utuh, cocok untuk sarapan.",
    price: 22000,
    stock: 5,
    imageUrl: "/products/roti-tawar-gandum.svg",
    category: "Roti Tawar",
  },
  {
    id: "roti-tawar-original",
    name: "Roti Tawar Original",
    description: "Tekstur empuk klasik, enak dimakan langsung atau dipanggang.",
    price: 18000,
    stock: 0,
    imageUrl: "/products/roti-tawar-original.svg",
    category: "Roti Tawar",
  },
  {
    id: "croissant-butter",
    name: "Croissant Butter",
    description: "Berlapis-lapis dan renyah di luar, lembut mentega di dalam.",
    price: 17000,
    stock: 6,
    imageUrl: "/products/croissant-butter.svg",
    category: "Pastry",
  },
  {
    id: "danish-blueberry",
    name: "Danish Blueberry",
    description: "Pastry berlapis dengan selai blueberry asam manis segar.",
    price: 19000,
    stock: 4,
    imageUrl: "/products/danish-blueberry.svg",
    category: "Pastry",
  },
  {
    id: "donat-gula",
    name: "Donat Gula",
    description: "Donat klasik empuk bertabur gula halus.",
    price: 8000,
    stock: 20,
    imageUrl: "/products/donat-gula.svg",
    category: "Donat",
  },
  {
    id: "donat-coklat-keju",
    name: "Donat Coklat Keju",
    description: "Donat dengan lelehan coklat dan taburan keju di atasnya.",
    price: 10000,
    stock: 0,
    imageUrl: "/products/donat-coklat-keju.svg",
    category: "Donat",
  },
  {
    id: "roti-sosis",
    name: "Roti Sosis",
    description: "Roti gurih isi sosis dan saus sambal mayo.",
    price: 13000,
    stock: 9,
    imageUrl: "/products/roti-sosis.svg",
    category: "Roti Manis",
  },
  {
    id: "roti-abon",
    name: "Roti Abon",
    description: "Roti gurih dengan taburan abon sapi dan mayones.",
    price: 14000,
    stock: 3,
    imageUrl: "/products/roti-abon.svg",
    category: "Roti Manis",
  },
];
